version: '3.3'

services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  db_data: null
  .: null